### ISSUE TITLE
Falta de pacote para release v2.1.3

### ISSUE THREAD

**Issue by thiagoinacioalves** [supergovbr/mod-sei-protocolo-integrado#15]
Não encontro pacote para para instalação da release 2.1.3, apenas a 3.0.0.
No sei atual do ministério do esporte, necessitamos da versão 2.1.3.

Foi retiro para download

(https://github.com/supergovbr/mod-sei-protocolo-integrado/releases/tag/sei-protocolo-integrado_v2.1.3)

**Comment by caduvieira** [comment]
Por favor seguir o readme de instalação rápida da versão 2.1.3 https://github.com/supergovbr/mod-sei-protocolo-integrado/tree/v2.1.3#instala%C3%A7%C3%A3o-r%C3%A1pida

Não havia, na época, o mecanismo que há para a geração do zip da release na versão 2.1.3.
