### ISSUE TITLE
Compatibilidade SUPER

### ISSUE THREAD

**Issue by evertramos** [supergovbr/mod-sei-protocolo-integrado#4]
Olá @marlinhares,

Estamos migrando para o SUPER e gostaria de saber se poderia liberar uma _branch_ com compatibilidade com o SUPER.

Obrigado!

**Comment by guilhermeadc** [comment]
Prezado @evertramos , 

Foi publicado a versão 3.0.0 com suporte ao SUPER. O link para maiores informações sobre esta versão pode ser acessado em https://github.com/supergovbr/mod-sei-protocolo-integrado/releases/tag/v3.0.0
