### ISSUE TITLE
Layout da tela de monitoramento quebrando dados 

### ISSUE THREAD

**Issue by renatovianadef** [supergovbr/mod-sei-protocolo-integrado#8]
**Descreva o erro**

Uma descrição clara e concisa do que é o erro.
Página de monitoramente apresenta falhas de configuração do layout antes e após a pesquisa

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para 'Adminsitração --> Protocolo Integrado --> Monitoramento' 
2. Clique em '....'
3. Versão SUPERBR: 4.0.34
4. Role para baixo até 'Pesquisar'
5. Veja o erro: Print enviado abaixo

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.
![Capturar](https://user-images.githubusercontent.com/111460962/203623355-8fe0bcbe-8655-4990-b718-84d8fa3eeabd.PNG)
![Capturar2](https://user-images.githubusercontent.com/111460962/203623368-1d66a80a-3d7e-4582-b68d-44358aca5710.PNG)

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: básico, administrador, etc.]
 - Banco de Dados: [ex: MySQL, Oracle, SqlServer, PostgreSQL] 

-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema.

**Comment by duanequintino** [comment]
Teste realizado junto ao Mateus, issue validada :)
